schoolproject/schoolapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from schoolapp import views
app_name='schoolapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('myfunctionq', views.myfunctionq, name='myfunctionq'),
    path('AllDepartment', views.AllDepartment, name='AllDepartment'),
    path('Getcourse', views.Getcourse, name='Getcourse'),
    path('register', views.register, name='register'),
    path('regform', views.regform, name='regform'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout')

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

schoolproject/schoolproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('schoolapp.urls','schoolapp'),namespace='schoolapp')),

]

schoolproject/schoolapp/models.py
from django.db import models

# Create your models here.

class Department(models.Model):
    name=models.CharField(max_length=250)

    class Meta:
        ordering=('name',)
        verbose_name='department'
        verbose_name_plural='departments'


    def __str__(self):
        return '{}'.format(self.name)
class Courses(models.Model):
    name = models.CharField(max_length=250)
    department = models.ForeignKey(Department,on_delete=models.CASCADE)

    class Meta:
        ordering=('name',)
        verbose_name='courses'
        verbose_name_plural='coursess'

    def __str__(self):
        return '{}'.format(self.name)

schoolproject/schoolapp/views.py
import alert as alert
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .models import Department,Courses


# Create your views here.
def index(request):
     return render(request,'index.html')

def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,"invalid credentials")
            return redirect('login')
    return render(request,"login.html")
def logout(request):
    auth.logout(request)
    return redirect('/')

def register(request):
    print(request.method)
    if request.method=='POST':
        username=request.POST['username']


        password = request.POST['password']
        confirmpassword = request.POST['confirmpassword']

        if password==confirmpassword:
           if User.objects.filter(username=username).exists():
                print("username already exists")
                messages.info(request,"USERNAME Already Exists...")
                return redirect('register')

           else:
                user = User.objects.create_user(username=username,password=password)
                user.save();
                print("User Created....")
                return render(request,"login.html")

        else:
         messages.info(request, "Password is not Matched")
         return render(request,"register.html")
    else:
        print("enter else case")
        messages.info(request, "Form is not in method POST")
        return render(request,"register.html")

def regform(request):
    return render(request,"regform.html")

def AllDepartment(request):

    departments = Department.objects.all()
    return render(request,'regform.html',{'department':departments})
def myfunctionq(request):


    return render(request,'confirm.html')
def Getcourse(request):
    print("inside...........")

    id=request.GET.get('deptmnt')
    print(id)
    course = Courses.objects.get(name=id)
    print("get cp")
    return render(request, 'regform.html', {'course': course})

schoolproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

schoolproject/templates/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>IT Tech</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">
</head>
<body>
<form method="POST">
    {% csrf_token %}
    <p>Order Confirmed</p>
    <button type="submit"><a href="{% url 'schoolapp:index' %}">Home</a></button>

</form>
</body>
</html>

schoolproject/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900' %}" rel="stylesheet">

    <title>IT Tech</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-edu-meeting.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lightbox.css' %}">
<!--

TemplateMo 569 Edu Meeting

https://templatemo.com/tm-569-edu-meeting

-->
  </head>

<body>

  <!-- Sub Header -->

  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky">
      <div class="container">
          <div class="row">
              <div class="col-12">
                  <nav class="main-nav">
                      <!-- ***** Logo Start ***** -->
                      <a href="index.html" class="logo">
                          IT Tech
                      </a>
                      <!-- ***** Logo End ***** -->
                      <!-- ***** Menu Start ***** -->
                      <ul class="nav">
                          <li class="scroll-to-section"><a href="#top" class="active">Home</a></li>


                          <li class="has-sub">
                              <a href="javascript:void(0)">Department</a>
                              <ul class="sub-menu">
                                  <li><a href="https://en.wikipedia.org/wiki/Bachelor_of_Business_Administration" target="_blank">BBA</a></li>
                                  <li><a href="https://en.wikipedia.org/wiki/Bachelor_of_Science_in_Information_Technology" target="_blank">BCA</a></li>
                                  <li><a href="https://en.wikipedia.org/wiki/Master_of_Business_Administration" target="_blank">MBA</a></li>
                                  <li><a href="https://en.wikipedia.org/wiki/Master_of_Science_in_Information_Technology" target="_blank">MCA</a></li>
                                  <li><a href="https://en.wikipedia.org/wiki/Master_of_Science_in_Information_Technology" target="_blank">Msc IT</a></li>
                              </ul>
                          </li>
                        {% if user.is_authenticated %}
									<li>Hello  {{user.username}}</li>
                                    <li><a href="{% url 'schoolapp:logout' %}">Logout</a></li>
                        <div class="main-button-red">
                  <div><a href="{% url 'schoolapp:regform' %}">Form</a></div>
              </div>

                        {% else %}
                           <li><a href="{% url 'schoolapp:login' %}">Login</a></li>
                            <li><a href="{% url 'schoolapp:register' %}">Register</a></li>
                        {% endif %}
                      </ul>
                      <a class='menu-trigger'>
                          <span>Menu</span>
                      </a>
                      <!-- ***** Menu End ***** -->
                  </nav>
              </div>
          </div>
      </div>
  </header>
  <!-- ***** Header Area End ***** -->

  <!-- ***** Main Banner Area Start ***** -->
  <section class="section main-banner" id="top" data-section="section1">
      <video autoplay muted loop id="bg-video">
          <source src="{% static 'assets/images/course-video.mp4' %}" type="video/mp4" />
      </video>

      <div class="video-overlay header-text">
          <div class="container">
            <div class="row">
              <div class="col-lg-12">
                <div class="caption">
              <h6>Hello Students</h6>
              <h2>Welcome to Education</h2>
<!--              <p>This is an edu meeting HTML CSS template provided by <a rel="nofollow" href="{% static 'https://templatemo.com/page/1' %}" target="_blank">TemplateMo website</a>. This is a Bootstrap v5.1.3 layout. The video background is taken from Pexels website, a group of young people by <a rel="nofollow" href="{% static 'https://www.pexels.com/@pressmaster' %}" target="_blank">Pressmaster</a>.</p>-->
              <p>Higher education is tertiary education leading to the award of an academic degree. Higher education, which makes up a component of post-secondary, third-level, or tertiary education, is an optional final stage of formal learning that occurs after completion of secondary education</p>

          </div>
              </div>
            </div>
          </div>
      </div>
  </section>
  <!-- ***** Main Banner Area End ***** -->

  <section class="services">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="owl-service-item owl-carousel">
          
            <div class="item">
              <div class="icon">
                <img src="{% static 'assets/images/service-icon-01.png' %}" alt="">
              </div>
              <div class="down-content">
                <h4>Best Education</h4>
                <p>Supporting Best Level</p>
              </div>
            </div>
            
            <div class="item">
              <div class="icon">
                <img src="{% static 'assets/images/service-icon-02.png' %}" alt="">
              </div>
              <div class="down-content">
                <h4>Best Teachers</h4>
                <p>Teachers from Commerce</p>
              </div>
            </div>
            
            <div class="item">
              <div class="icon">
                <img src="{% static 'assets/images/service-icon-03.png' %}" alt="">
              </div>
              <div class="down-content">
                <h4>Best Students</h4>
                <p>Student in MCA is Vibin</p>
              </div>
            </div>
            

            
            <div class="item">
              <div class="icon">
                <img src="{% static 'assets/images/service-icon-03.png' %}" alt="">
              </div>
              <div class="down-content">
                <h4>Best Networking</h4>
                <p>Networking Faculty</p>
              </div>
            </div>
            
          </div>
        </div>
      </div>
    </div>
  </section>



  <section class="our-courses" id="courses">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="section-heading">
            <h2>Our Popular Courses</h2>
          </div>
        </div>
        <div class="col-lg-12">
          <div class="owl-courses-item owl-carousel">
            <div class="item">
              <img src="{% static 'assets/images/course-01.jpg' %}" alt="Course One">
              <div class="down-content">
                <h4>BCA stands for Bachelor of Computer Application. It is a three-year undergraduate course that focuses on the basics of computer application and software development</h4>
                <div class="info">
                  <div class="row">
                    <div class="col-8">
                      <ul>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                      </ul>
                    </div>
                    <div class="col-4">
                       <span>$160</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="item">
              <img src="{%static 'assets/images/course-02.jpg' %}" alt="Course Two">
              <div class="down-content">
                <h4>If you mean MCA as a course, it stands for Master of Computer Applications. It is a postgraduate course that trains students in the various aspects of computer programs, application software, computer architecture, operating systems and many more</h4>
                <div class="info">
                  <div class="row">
                    <div class="col-8">
                      <ul>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                      </ul>
                    </div>
                    <div class="col-4">
                       <span>$180</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="item">
              <img src="{% static 'assets/images/course-03.jpg' %}" alt="">
              <div class="down-content">
                <h4>BBA stands for Bachelor of Business Administration. It is a three-year undergraduate degree programme in the field of business administration and management1. It covers subjects such as accounting, economics, finance, marketing, management, and more</h4>
                <div class="info">
                  <div class="row">
                    <div class="col-8">
                      <ul>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                      </ul>
                    </div>
                    <div class="col-4">
                       <span>$140</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="item">
              <img src="{% static 'assets/images/course-04.jpg' %}" alt="">
              <div class="down-content">
                <h4>A Master of Business Administration is a postgraduate degree focused on business administration. The core courses in an MBA program cover various areas of business administration</h4>
                <div class="info">
                  <div class="row">
                    <div class="col-8">
                      <ul>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                      </ul>
                    </div>
                    <div class="col-4">
                       <span>$120</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </section>




  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <script src="{% static 'assets/js/isotope.min.js' %}"></script>
    <script src="{% static 'assets/js/owl-carousel.js' %}"></script>
    <script src="{% static 'assets/js/lightbox.js' %}"></script>
    <script src="{% static 'assets/js/tabs.js' %}"></script>
    <script src="{% static 'assets/js/video.js' %}"></script>
    <script src="{% static 'assets/js/slick-slider.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script>
        //according to loftblog tut
        $('.nav li:first').addClass('active');

        var showSection = function showSection(section, isAnimate) {
          var
          direction = section.replace(/#/, ''),
          reqSection = $('.section').filter('[data-section="' + direction + '"]'),
          reqSectionPos = reqSection.offset().top - 0;

          if (isAnimate) {
            $('body, html').animate({
              scrollTop: reqSectionPos },
            800);
          } else {
            $('body, html').scrollTop(reqSectionPos);
          }

        };

        var checkSection = function checkSection() {
          $('.section').each(function () {
            var
            $this = $(this),
            topEdge = $this.offset().top - 80,
            bottomEdge = topEdge + $this.height(),
            wScroll = $(window).scrollTop();
            if (topEdge < wScroll && bottomEdge > wScroll) {
              var
              currentId = $this.data('section'),
              reqLink = $('a').filter('[href*=\\#' + currentId + ']');
              reqLink.closest('li').addClass('active').
              siblings().removeClass('active');
            }
          });
        };

        $('.main-menu, .responsive-menu, .scroll-to-section').on('click', 'a', function (e) {
          e.preventDefault();
          showSection($(this).attr('href'), true);
        });

        $(window).scroll(function () {
          checkSection();
        });
    </script>
</body>

</body>
</html>

schoolproject/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>IT Tech</title>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900' %}" rel="stylesheet">
 <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
 <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-edu-meeting.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lightbox.css' %}">

</head>
<body style="background-image:url('static/assets/images/img_1.png')" >
<h3>Login Form</h3>
<form action="login" method="POST">
    {% csrf_token %}
    <div class="container">
    <div class="row">
        <div class="col-md-6">
             <div class="form-group">
                    <label for="formGroupExampleInput">User Name </label>
                    <input type="text" class="form-control" id="formGroupExampleInput"  name="username" placeholder="Enter UserName">
                </div><br><br>
             <div class="form-group">
                    <label for="formGroupExampleInput">Password </label>
                    <input type="password" class="form-control" id="formGroupExampleInput1" name="password" placeholder="Enter Password">
                </div><br><br><br><br>

<!--    <input type="text" name="username" id="username" autocomplete="off" placeholder="UserName"><br>-->
<!--    <input type="text" name="password" id="password" autocomplete="off" placeholder="password"><br>-->
    <input type="submit" class="btn btn-success">
        </div>
    </div>
    </div>
</form>
</body>
</html>

schoolproject/templates/regform.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>IT Tech</title>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
     <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
     <title>IT Tech</title>


    <!-- Additional CSS Files -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-edu-meeting.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lightbox.css' %}">

</head><h3>Registration Form</h3>
<body style="background-image:url('static/assets/images/img_1.png')" >
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form action="regform" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="formGroupExampleInput">Name </label>
                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Enter Name">
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput">Date of Birth </label>
                    <input type="date" class="form-control" id="formGroupExampleInput1">
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput">Age </label>
                    <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Enter Age">
                </div>
                <label>Gender</label><br>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
                    <label class="form-check-label" for="flexRadioDefault1">
                    Male
                    </label>
                </div>
<div class="form-check">
  <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
  <label class="form-check-label" for="flexRadioDefault2">
    Female
  </label>
</div>



      <div class="form-group">
    <label for="formGroupExampleInput">Phone Number </label>
    <input type="text" class="form-control" id="formGroupExampleInput3" placeholder="Enter Phone Number">
  </div>
      <div class="form-group">
    <label for="formGroupExampleInput">Email </label>
    <input type="email" class="form-control" id="formGroupExampleInput4" placeholder="Enter Email">
  </div>
      <div class="form-group">
    <label for="formGroupExampleInput">Address </label>
    <input type="text" class="form-control" id="formGroupExampleInput5" placeholder="Enter Address">
  </div>

<!--        <div class="dropdown-menu" id="depts">-->
<!--             All Departments-->
<!--               {% for dept in department %}-->
<!--                 {{dept.name}}-->
<!--               {% endfor %}-->
<!--            </div>-->
<a href="{% url 'schoolapp:AllDepartment' %}">Departments</a>



<select class="form-control" name="deptmnt" id="deptmnt" >
               {% for dept in department %}

                 <option value=" {{dept.name}} " >{{dept.name}}</option>
               {% endfor %}
 </select>
          <br>

       <a href="{% url 'schoolapp:Getcourse' %}">Courses</a>
<!--      <select class="form-select form-select-sm" aria-label="Small select example">-->
                <select class="form-control" >
          {% for depts in course %}
          <option value=" {{depts.id}} ">{{depts.name}}</option>
{% endfor %}

</select><br>
<!--                {% for dept in department %}-->
<!--                  <li><a class="dropdown-item">{{dept.name}}</a></li>-->
<!--               {% endfor %}-->






      <label>Purpose:</label>
<select class="form-select form-select-sm" aria-label="Small select example">
  <option selected>Open this select menu</option>

  <option value="enquiry">For Enquiry</option>
  <option value="placeorder">Place Order</option>
  <option value="return">Return</option>
  <option value="cancelorder">Cancel Order</option>
</select><br>
    <label>Materials Provide</label><br>

    <label>Debit Note Book</label><input type="checkbox" name="dnb" id="dnb" value="Debit Note Book">&nbsp;&nbsp;
    <label>Pen</label><input type="checkbox" name="pen" id="pen" value="Pen">&nbsp;&nbsp;
          <label>Exam Pappers</label><input type="checkbox" name="expappers" id="expappers" value="Exam Pappers"><br>


               <div>   <div class="main-button-red">
                    <a href="{% url 'schoolapp:myfunctionq' %}">Submit</a></div>&nbsp;
                <div class="main-button-red">
                  <a href="{% url 'schoolapp:logout' %}">LogOut</a></div>
    </div>

  </form>
        </div>
    </div>
</div>
<script src="{% static 'assets/js/popper.min.js' %}">

</script>
</body>
</html>

schoolproject/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>IT Tech</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900' %}" rel="stylesheet">
 <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
 <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-edu-meeting.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lightbox.css' %}">
</head>
<body style="background-image:url('static/assets/images/img_1.png')" >
<h3>Register Form</h3>

<form action="register" method="POST">
    {% csrf_token %}
    <div class="container">
    <div class="row">
        <div class="col-md-6">
     <div class="form-group">
                    <label for="formGroupExampleInput">User Name </label>
                    <input type="text" class="form-control" id="formGroupExampleInput"  name="username" placeholder="Enter UserName">
                </div><br><br>
     <div class="form-group">
                    <label for="formGroupExampleInput">Password </label>
                    <input type="password" class="form-control" id="formGroupExampleInput1"  name="password" placeholder="Enter UserName">
                </div><br><br>
     <div class="form-group">
                    <label for="formGroupExampleInput">Confirm Password </label>
                    <input type="text" class="form-control" id="formGroupExampleInput2"  name="confirmpassword" placeholder="Enter UserName">
                </div><br><br>

    <input type="submit" class="btn btn-success" >
        </div>
    </div>
    </div>
</form>

</body>
</html>